const SET_KEYWORD = 'SET_KEYWORD';
const RESET_KEYWORD = 'RESET_KEYWORD';
const FETCH_SEARCH_RESULT = 'FETCH_SEARCH_RESULT';
const GET_SEARCH_RESULT = 'GET_SEARCH_RESULT';

export { SET_KEYWORD, RESET_KEYWORD, FETCH_SEARCH_RESULT, GET_SEARCH_RESULT };
