const FETCH_SEARCH_RESULT = 'FETCH_SEARCH_RESULT';
const GET_SEARCH_RESULT_SUCCESS = 'GET_SEARCH_RESULT_SUCCESS';
const GET_SEARCH_RESULT_ERROR = 'GET_SEARCH_RESULT_ERROR';

export {
  FETCH_SEARCH_RESULT,
  GET_SEARCH_RESULT_SUCCESS,
  GET_SEARCH_RESULT_ERROR,
};
