export const FETCH_SEARCH_RESULT = 'FETCH_SEARCH_RESULT' as const;
export const GET_SEARCH_RESULT_SUCCESS = 'GET_SEARCH_RESULT_SUCCESS' as const;
export const GET_SEARCH_RESULT_ERROR = 'GET_SEARCH_RESULT_ERROR' as const;
export const GET_NO_RESULT = 'GET_NO_RESULT' as const;
